// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PaymentGateway.Bank.RestClient
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// </summary>
    public partial interface IPaymentGatewayBankMock : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <param name='cardInfoCardNumber'>
        /// </param>
        /// <param name='cardInfoCvv'>
        /// </param>
        /// <param name='cardInfoHolderName'>
        /// </param>
        /// <param name='cardInfoExpiryMonth'>
        /// </param>
        /// <param name='cardInfoExpiryYear'>
        /// </param>
        /// <param name='amount'>
        /// </param>
        /// <param name='currencyCode'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ProcessPaymentWithHttpMessagesAsync(string cardInfoCardNumber = default(string), string cardInfoCvv = default(string), string cardInfoHolderName = default(string), int? cardInfoExpiryMonth = default(int?), int? cardInfoExpiryYear = default(int?), double? amount = default(double?), string currencyCode = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
